#arquivo com comandos Python básico
print("Comando print, imprimi uma mensagem na tela")
print("Olá mundo!")
print("------------------------------------------")
print("No Python temos alguns tipos de dados, dentre eles:")
print("String")
print("2")
print("Tato")
print("---------------")
print("inteiros")
print(23)
print(29102)
print("---------------")
print("float")
print(24.45)
print(3.1415)
print("---------------")
print("Boolean")
print (7 > 1)
print (1 == 3)

