#Operações matemáticas em Python
#Para outras resoluções matemáticas usar a biblioteca math
print("Operações matemáticas com python")
print("-"*20)
print("Adição")
print("-"*20)
print("A soma de 5 + 2 é")
print(5+2)
print("-"*20)
print("Subtração")
print("-"*20)
print("A subtração de 5 - 2 é")
print(5-2)
print("-"*20)
print("Multiplicação")
print("-"*20)
print("A multiplicação de 5 x 2 é")
print(5*2)
print("-"*20)
print("Divisão")
print("-"*20)
print("A divisão de 6 : 2 é")
print(6/2)
print("-"*20)
print("Exponenciação")
print("-"*20)
print("5 elevado ao quadrado é igual à")
print(5**2)
print("-"*20)
print("Resto da divisão ou modulo")
print("-"*20)
print("O resto da divisão de 5 : 2 é")
print(5%2)
print("-"*20)
